Update update-data.yml

diff --git a/.github/workflows/update-data.yml b/.github/workflows/update-data.yml
--- a/.github/workflows/update-data.yml
+++ b/.github/workflows/update-data.yml
@@ -16,61 +16,21 @@ jobs:
       contents: write
 
     steps:
-      - name: Get Date
-        id: get-date
-        run: |
-          echo "date=$(/bin/date \"+%Y%m%dT%H%M%S\")" >> $GITHUB_OUTPUT
-        shell: bash
-
-      - name: Checkout Repo
-        uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: "3.13"
-          cache: "pipenv"
-
-      - name: Cache Scrapes
-        uses: actions/cache@v4
-        with:
-          path: ${{ runner.temp }}/_working/_cache
-          key: cache-scrapes-key-${{ steps.get-date.outputs.date }}
-          restore-keys: |
-            cache-scrapes-key-
-
-      - name: Scrape Data
-        run: |
-          docker pull openstates/scrapers:28675b011eef5bb35a758d05d1b7313d515c28ea
-          mkdir -p ${RUNNER_TEMP}/_working
-          docker run \
-              -v "${RUNNER_TEMP}/_working/_data":/opt/openstates/openstates/_data \
-              -v "${RUNNER_TEMP}/_working/_cache":/opt/openstates/openstates/_cache \
-              openstates/scrapers:28675b011eef5bb35a758d05d1b7313d515c28ea \
-              $STATE bills --scrape --fastmode
-
-      - name: Sanitize Data (removes _id and scraped_at)
-        run: |
-          find ${RUNNER_TEMP}/_working/_data -type f -name "*.json" -exec bash -c 'jq "del(..|._id?, .scraped_at?)" "{}" > "{}.tmp" && mv "{}.tmp" "{}"' \;
-
-      - name: Format Data
-        uses: windy-civi/opencivicdata-blockchain-transformer@main
+      - uses: windy-civi/opencivicdata-blockchain-transformer@main
         with:
            state: ${{ env.STATE }}
            input-folder: ${{ runner.temp }}/_working/_data/${{ env.STATE }}
            allow-session-fix: true
 
-      - name: Update Repo
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          git config user.email "no_email"
-          git config user.name "Windy Civi Bot"
-          git fetch origin main
-          git pull origin main --rebase || true
+      # - name: Update Repo
+      #   env:
+      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #     git config user.email "no_email"
+      #     git config user.name "Windy Civi Bot"
+      #     git fetch origin main
+      #     git pull origin main --rebase || true
 
-          git add data_output bill_session_mapping sessions
-          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Automated report update (report dated ${{ steps.get-date.outputs.date }})"
-          git push || echo "⚠️ Git push failed — possibly due to upstream changes."
+      #     git add data_output bill_session_mapping sessions
+      #     git diff --cached --quiet && echo "No changes to commit" || git commit -m "Automated report update (report dated ${{ steps.get-date.outputs.date }})"
+      #     git push || echo "⚠️ Git push failed — possibly due to upstream changes."
